export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR   = 'FETCH_CATEGORIES_ERROR';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_ERROR   = 'FETCH_ITEMS_ERROR';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_ERROR   = 'FETCH_ORDER_ERROR';

export const ADD_TO_ORDER_REQUEST = 'ADD_TO_ORDER_REQUEST';
export const ADD_TO_ORDER_SUCCESS = 'ADD_TO_ORDER_SUCCESS';
export const ADD_TO_ORDER_ERROR   = 'ADD_TO_ORDER_ERROR';

export const INCREASE_ORDER_ITEM_REQUEST = 'INCREASE_ORDER_ITEM_REQUEST';
export const INCREASE_ORDER_ITEM_SUCCESS = 'INCREASE_ORDER_ITEM_SUCCESS';
export const INCREASE_ORDER_ITEM_ERROR   = 'INCREASE_ORDER_ITEM_ERROR';

export const REDUCE_ORDER_ITEM_REQUEST = 'REDUCE_ORDER_ITEM_REQUEST';
export const REDUCE_ORDER_ITEM_SUCCESS = 'REDUCE_ORDER_ITEM_SUCCESS';
export const REDUCE_ORDER_ITEM_ERROR   = 'REDUCE_ORDER_ITEM_ERROR';

export const DELETE_ORDER_ITEM_REQUEST = 'DELETE_ORDER_ITEM_REQUEST';
export const DELETE_ORDER_ITEM_SUCCESS = 'DELETE_ORDER_ITEM_SUCCESS';
export const DELETE_ORDER_ITEM_ERROR   = 'DELETE_ORDER_ITEM_ERROR';

